# Generated by Django 5.0.2 on 2025-03-16 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adminlocation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='adminlocation',
            name='admin',
            field=models.OneToOneField(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_admins', to='accounts.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(choices=[('TAMIL_NADU', 'Tamil Nadu'), ('ANDHRA_PRADESH', 'Andhra Pradesh'), ('TELANGANA', 'Telangana'), ('ODISHA', 'Odisha')], max_length=20, unique=True),
        ),
    ]
